name: rag-sys
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - nvidia::cuda-toolkit
  - conda-forge::accelerate
  - conda-forge::poppler
  - libmagic
  - tesseract
  - pip
  - pip:
      - uv
