apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-sys
resources:
  - namespace.yml
  - elasticsearch/pvc.yml
  - elasticsearch/deployment.yml
  - elasticsearch/service.yml
  - api/configmap.yml
  - api/deployment.yml
  - api/service.yml