apiVersion: v1
kind: Service
metadata:
  name: rag-sys-api
  namespace: rag-sys
spec:
  selector:
    app: rag-sys-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
